# Generated by Django 5.0.14 on 2026-07-03 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=20)),
                ('latitude', models.FloatField(help_text='Decimal degrees, e.g. 18.5204')),
                ('longitude', models.FloatField(help_text='Decimal degrees, e.g. 73.8567')),
                ('address', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workshop', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=20)),
                ('customer_complaint', models.TextField()),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('IN_PROGRESS', 'In-Progress'), ('WAITING_FOR_PARTS', 'Waiting-for-Parts'), ('COMPLETED', 'Completed')], default='RECEIVED', max_length=20)),
                ('total_bill', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_cards', to='workshop.workshopprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=150)),
                ('sku', models.CharField(blank=True, max_length=60)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('b2b_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='workshop.workshopprofile')),
            ],
            options={
                'ordering': ['part_name'],
            },
        ),
    ]
