# Generated by Django 5.0.14 on 2026-07-04 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcard',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'Received'), ('IN_PROGRESS', 'In-Progress'), ('WAITING_FOR_PARTS', 'Waiting-for-Parts'), ('READY', 'Ready')], default='RECEIVED', max_length=20),
        ),
    ]
