# Generated by Django 5.0.14 on 2026-07-07 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_alter_jobcard_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCardLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=150)),
                ('sku', models.CharField(blank=True, max_length=60)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inventory_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='line_items', to='workshop.inventoryitem')),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='workshop.jobcard')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
