# Generated by Django 5.0.14 on 2026-07-07 13:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0003_jobcardlineitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopprofile',
            name='latitude',
            field=models.FloatField(help_text='Decimal degrees, e.g. 18.5204', validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)]),
        ),
        migrations.AlterField(
            model_name='workshopprofile',
            name='longitude',
            field=models.FloatField(help_text='Decimal degrees, e.g. 73.8567', validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)]),
        ),
    ]
