# Generated by Django 5.0.14 on 2026-07-07 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0004_alter_workshopprofile_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_charges', to='workshop.jobcard')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobCardActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('CREATED', 'Job Card Created'), ('PART_ADDED', 'Part Added'), ('PART_REMOVED', 'Part Removed'), ('STATUS_CHANGED', 'Status Changed'), ('CHARGE_ADDED', 'Charge Added'), ('CHARGE_REMOVED', 'Charge Removed'), ('INVOICE_GENERATED', 'Invoice Generated')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='workshop.jobcard')),
            ],
            options={
                'verbose_name_plural': 'job card activities',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
